language: php

php:
  - 7.4
  - 8.0

env:
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files


before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer config  extra.symfony.require "${SYMFONY_VERSION}"
  - composer update --prefer-dist

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com
