language: php

php:
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files


before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install: composer update --prefer-dist

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com
