name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        symfony-version:
          - '^3.4'
          - '^4.4'
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
#        include:
#          - { php-version: '8.2', dependencies: 'highest', composer-options: '--ignore-platform-req=php' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Configure symfony version
        uses: php-actions/composer@v6
        with:
          command: config
          args:
            - extra.symfony.require
            - "${{ symfony-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"

      - name: Run tests
        run: |
          SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}
